# Create a sample project in rundeck using Auth-method
- name: Create Rundeck Sample project with API authentication
  command: curl -X POST -H x-rundeck-auth-token:{{ RUNDECK_AUTH_TOKEN }} http://{{ RUNDECK_SERVER }}:4440/api/21/projects -H "Content-Type:application/json" -d '{ "name":"{{ PROJECT_NAME }}", "config":{ "propname":"propvalue" } }'
